### PR TITLE
feat(inv bar): remove useless check

### PR DESCRIPTION
**Pull request by Prakkkmak**

### CODE REVIEW

**Review by Nowp — COMMENTED** [review]
Why is it useless?

**Comment by Prakkkmak** [comment]
> Why is it useless?

Because we never create a Local.Pawn who is not MainPlayer

**Comment by Nowp** [comment]
Yeah but if MainPlayer is not yet instantiated, does the UI is created ?

**Comment by Prakkkmak** [comment]
> Yeah but if MainPlayer is not yet instantiated, does the UI is created ?

If it is, we want to catch this error because we don't handle that.

**Review by Nowp — APPROVED** [review]

**Pull request merged**
