### PR TITLE
Selector

### PR DESCRIPTION
**Pull request by Prakkkmak**

### CODE REVIEW

**Comment by Prakkkmak** [comment]
[World interaction](https://trello.com/c/Y6fADhoq/108-world-interaction)

**Review by Nowp — COMMENTED** [review]
Selector is a bad name in my opinion

**Comment by Prakkkmak** [comment]
> Selector is a bad name in my opinion

What do you propose instead then ?

**Comment by Nowp** [comment]
> > Selector is a bad name in my opinion
> 
> What do you propose instead then ?

WorldInteract or something with interact, if you don't like it we can keep selector it's just that it seems like a "click and drag" select

**Review by Nowp — APPROVED** [review]

**Pull request merged**
